=== alummanuelgarcia/XMLRepo/clientes/clientes.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT clientes (sede*)>
<!ELEMENT sede (codigosede|nombreempleado|fecha|descripcion|codigocliente)>
<!ELEMENT codigosede (#PCDATA)>
<!ELEMENT nombreempleado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cliente (codigo|numviviendas|coste|resumen|plazo)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT numviviendas (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== alummanuelgarcia/XMLRepo/clientes/clientes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="A1234567">        
        <nombreempleado>Juan</nombreempleado>
        <fecha>12/12/2001</fecha>
        <descripcion>Solvente</descripcion>
        <cliente codigo="ABC 123">                       
            <numviviendas>4</numviviendas>
            <coste>5000</coste>
            <resumen>Chalet pequeno</resumen>
            <plazo>2 meses</plazo>
        </cliente>
    </sede>
</clientes>
