=== alummanuelgarcia/XMLRepo/clientes/clientes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sede" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo" type="xs:integer" />
                            <xs:element name="nombreempleado" type="xs:string" />
                            <xs:element name="fecha" type="xs:string" />
                            <xs:element name="descripcion" type="xs:string" />
                            <xs:element name="cliente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="numviviendas" type="xs:integer" />
                                        <xs:element name="coste" type="xs:integer" />                                       
                                        <xs:element name="resumen" type="xs:string" />
                                        <xs:element name="plazo" type="xs:string" />
                                    <xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alummanuelgarcia/XMLRepo/clientes/clientes2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clientes.xsd">
    <sede codigo="A1234567">        
        <nombreempleado>Juan</nombreempleado>
        <fecha>12/12/2001</fecha>
        <descripcion>Solvente</descripcion>
        <cliente codigo="ABC 123">                       
            <numviviendas>4</numviviendas>
            <coste>5000</coste>
            <resumen>Chalet pequeno</resumen>
            <plazo>2 meses</plazo>
        </cliente>
    </sede>
</clientes>
